name: simple_rest

description: Get your REST API server up and running in no time with our user-friendly quickstart package, designed for easy initialization in just a few simple steps.
version: 0.3.6
repository: https://github.com/JhonaCodes/simple_rest
homepage: https://jhonacode.com

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  args: ^2.4.1
  logger: ^1.3.0
  dart_jsonwebtoken: ^2.8.1
  mime: ^1.0.4


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
