name: simple_rest

description: A Simple library for api rest.
version: 1.1.2
repository: https://github.com/JhonaCodes/simple_rest
homepage: https://jhonacode.com

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  args: ^2.3.0
  logger: ^1.3.0
  supabase: ^1.6.3
  dart_jsonwebtoken: ^2.7.1


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
