name: simple_rest
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  args: ^2.3.0
  logger: ^1.3.0
  supabase: ^1.6.3
  dart_jsonwebtoken: ^2.7.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
